[env:esp32-s3-sidecar]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM
lib_deps =
    bblanchon/ArduinoJson @ ^7.4.2
