[platformio]
default_envs = hub-clock

[env:hub-clock]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/ttyACM0
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  moononournation/GFX Library for Arduino@1.4.7
